/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sun_ndk1_MainActivity */

#ifndef _Included_com_sun_ndk1_MainActivity
#define _Included_com_sun_ndk1_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sun_ndk1_MainActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sun_ndk1_MainActivity_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_sun_ndk1_MainActivity
 * Method:    getJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sun_ndk1_MainActivity_getJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_sun_ndk1_MainActivity
 * Method:    show
 * Signature: (ZBSIJFDC)V
 */
JNIEXPORT void JNICALL Java_com_sun_ndk1_MainActivity_show
  (JNIEnv *, jobject, jboolean, jbyte, jshort, jint, jlong, jfloat, jdouble, jchar);

/*
 * Class:     com_sun_ndk1_MainActivity
 * Method:    getBoolean
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_sun_ndk1_MainActivity_getBoolean
  (JNIEnv *, jobject);

/*
 * Class:     com_sun_ndk1_MainActivity
 * Method:    getByte
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_com_sun_ndk1_MainActivity_getByte
  (JNIEnv *, jobject);

/*
 * Class:     com_sun_ndk1_MainActivity
 * Method:    getShort
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_com_sun_ndk1_MainActivity_getShort
  (JNIEnv *, jobject);

/*
 * Class:     com_sun_ndk1_MainActivity
 * Method:    getInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_sun_ndk1_MainActivity_getInt
  (JNIEnv *, jobject);

/*
 * Class:     com_sun_ndk1_MainActivity
 * Method:    getLong
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_sun_ndk1_MainActivity_getLong
  (JNIEnv *, jobject);

/*
 * Class:     com_sun_ndk1_MainActivity
 * Method:    getFloat
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_sun_ndk1_MainActivity_getFloat
  (JNIEnv *, jobject);

/*
 * Class:     com_sun_ndk1_MainActivity
 * Method:    getDouble
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_sun_ndk1_MainActivity_getDouble
  (JNIEnv *, jobject);

/*
 * Class:     com_sun_ndk1_MainActivity
 * Method:    getChar
 * Signature: ()C
 */
JNIEXPORT jchar JNICALL Java_com_sun_ndk1_MainActivity_getChar
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
