/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sun_ndk1_MainActivity */

#ifndef _Included_com_sun_ndk1_MainActivity
#define _Included_com_sun_ndk1_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sun_ndk1_MainActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sun_ndk1_MainActivity_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_sun_ndk1_MainActivity
 * Method:    getNDK
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sun_ndk1_MainActivity_getNDK
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
